Fix: Absolut Path generation on Linux when using dgdecnv (#1089)
Hi,

this small PR fixes an issue, that occurs when using dgdecnv on a linux
system (Arch Linux 6.15.5-arch1-1 in my case). When starting av1an like
this `av1an -i test.mkv -o output.mkv -m dgdecnv`, av1an crashes with a
file not found error:

> Error: No such file or directory (os error 2)

After checking av1an with strace -f, I could see that av1an was trying
to access the temp directory at a point in time, when it was not created
yet.

Stepping through the code, I could pin point it to the
`to_absolute_path` method, that uses `path.canonicalize()` under linux.
This method does not seem to work on files (or directories) that are
non-existant. Unfortunately, `to_absolut_path` is called in
`vapoursynth.rs` for dgdecnv before the temp directories have been
created.

Instead of changing the order of initialization i just removed the
inline function and changed the code to use `absolute(path)` for all
operating systems. This function seems to work just fine under linux.